### ISSUE TITLE
Selecting on encrypted field with hash doesn't work in playwright

### ISSUE THREAD

**Issue by NGimbal** [47ng/prisma-field-encryption#121]
Thanks for your hard work on this library 🙏

I just want to log an issue I've run into a couple times now as much for myself as others. If I find time to explore further I will post more information here.

I've found that selecting by an encrypted field with a hash doesn't work in playwright tests and the field is not properly decrypted when the object is returned from the db. Strangely this issue is very infuriating because it does work when using the VSCode debugger and in production.

Sorry this is a little light on details, but I wanted to plant a little flag in the ground about this problem. Thanks again!

**Comment by franky47** [comment]
I'd love it if you managed to isolate that one, as I don't see what Playwright might do differently than a normal Node.js runtime, as long as the client is correctly extended/middleware'd.

Maybe the [logs](https://github.com/47ng/prisma-field-encryption#debugging) might help you out here.

**Comment by NGimbal** [comment]
Thanks for the response! Good tip about the logs.

Unfortunately I'm a huge idiot and this was actually my fault... or maybe not, but this issue is definitely wrong. This library totally works in playwright. I had purposefully disabled it while testing because of other incompatibilities... that I now want to chase down. Thanks again for this library! It's been super helpful... one of those things that really "just works." 🙏
