### ISSUE TITLE
ZodError when initializing PrismaClient

### ISSUE THREAD

**Issue by MonkeeMan1** [47ng/prisma-field-encryption#131]
Hello,

I'm currently trying to integrate this libary into my database, I am on version `"prisma-field-encryption": "^1.6.0"` and am getting the following error when trying to init the prisma client with this lib.

```typescript
dashboard:dev:  ⨯ ZodError: [
dashboard:dev:   {
dashboard:dev:     "code": "invalid_type",
dashboard:dev:     "expected": "object",
dashboard:dev:     "received": "undefined",
dashboard:dev:     "path": [],
dashboard:dev:     "message": "Required"
dashboard:dev:   }
dashboard:dev: ]
```

```typescript
const client = new p.PrismaClient();

console.log(env.PRISMA_FIELD_ENCRYPTION_KEY); // example output: k1.aesgcm256.DbQoar8ZLuUsOHZNyrnjlskInHDYlzF3q6y1KGM7DUM=

export const db = client.$extends(
  fieldEncryptionExtension({
    encryptionKey: env.PRISMA_FIELD_ENCRYPTION_KEY,
  })
) as p.PrismaClient;
```

I have checked the output of `env.PRISMA_FIELD_ENCRYPTION_KEY` and can confirm that it is not undefined. It outputs a cloak secret key similar to the example in your README - `k1.aesgcm256.DbQoar8ZLuUsOHZNyrnjlskInHDYlzF3q6y1KGM7DUM=`

An example of my prisma schema can be found below.

```
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider  = "postgresql"
  url       = env("DATABASE_URL")
}

model CustomInstance {
  id             Int            @id @default(autoincrement())
  guildId        String         @unique
  token          String /// @encrypted

  createdAt DateTime @default(now())
}
```

The Zod error isn't very helpful as it doesn't say what key name is the wrong type, at first I thought it was the `PRISMA_FIELD_ENCRYPTION_KEY` environment variable, but after double checking it is not that, as I get he correct output from it, i also tried hard coding the secret just encase and I still get the same Zod error.

The reason I know why it is this libary causing the issue is because when I remove the `fieldEncryptionExtension` function call I do not get the error, and I also get this traceback in my nextjs application:
![image](https://github.com/user-attachments/assets/259998e9-ae49-4c08-8086-a377622d9867)

If there is anymore information that I can provide please let me know :)

**Comment by franky47** [comment]
What's your Prisma version?

You may have more luck seeing what's going on with logging: https://github.com/47ng/prisma-field-encryption#debugging

The Zod error indicates an object being missing, could that be the dmmf? Looks like you're importing your Prisma client from a `p` namespace, maybe passing the dmmf from that could help?

```ts
export const db = client.$extends(
  fieldEncryptionExtension({
    encryptionKey: env.PRISMA_FIELD_ENCRYPTION_KEY,
    dmmf: p.dmmf
  })
) as p.PrismaClient;
```

**Comment by MonkeeMan1** [comment]
> What's your Prisma version?
> 
> You may have more luck seeing what's going on with logging: https://github.com/47ng/prisma-field-encryption#debugging
> 
> The Zod error indicates an object being missing, could that be the dmmf? Looks like you're importing your Prisma client from a `p` namespace, maybe passing the dmmf from that could help?
> 
> ```ts
> export const db = client.$extends(
>   fieldEncryptionExtension({
>     encryptionKey: env.PRISMA_FIELD_ENCRYPTION_KEY,
>     dmmf: p.dmmf
>   })
> ) as p.PrismaClient;
> ```

Hi, I am currently on prisma version `"prisma": "5.21.1",`. I have enabled logging for your library, the output can be seen below:
```typescript
bot:dev: 2024-10-27T21:34:25.936Z prisma-field-encryption:setup Keys: {
bot:dev:   encryptionKey: {
bot:dev:     raw: Uint8Array(32) [...],
bot:dev:     fingerprint: '...'
bot:dev:   },
bot:dev:   keychain: { dfd6b438: { key: [Object], createdAt: 1730064865935 } }
bot:dev: }
bot:dev: C:\Users\ben\OneDrive\Desktop\remake\node_modules\.pnpm\zod@3.23.8\node_modules\zod\lib\types.js:55
bot:dev:                 const error = new ZodError_1.ZodError(ctx.common.issues);
bot:dev:                               ^
bot:dev:
bot:dev: ZodError: [
bot:dev:   {
bot:dev:     "code": "invalid_type",
bot:dev:     "expected": "object",
bot:dev:     "received": "undefined",
bot:dev:     "path": [],
bot:dev:     "message": "Required"
bot:dev:   }
bot:dev: ]
bot:dev:     at get error [as error] (C:\Users\ben\OneDrive\Desktop\remake\node_modules\.pnpm\zod@3.23.8\node_modules\zod\lib\types.js:55:31)
bot:dev:     at ZodReadonly.parse (C:\Users\ben\OneDrive\Desktop\remake\node_modules\.pnpm\zod@3.23.8\node_modules\zod\lib\types.js:160:22)
bot:dev:     at analyseDMMF (C:\Users\ben\OneDrive\Desktop\remake\node_modules\.pnpm\prisma-field-encryption@1.6.0_@prisma+client@5.16.1_prisma@5.21.1_\node_modules\prisma-field-encryption\dist\dmmf.js:8:45)
bot:dev:     at fieldEncryptionExtension (C:\Users\ben\OneDrive\Desktop\remake\node_modules\.pnpm\prisma-field-encryption@1.6.0_@prisma+client@5.16.1_prisma@5.21.1_\node_modules\prisma-field-encryption\dist\extension.js:12:43)
bot:dev:     at file:///C:/Users/ben/OneDrive/Desktop/remake/apps//dist/database.js:5:35
bot:dev:     at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
bot:dev:     at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
bot:dev:     at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:123:5) {
bot:dev:   issues: [
bot:dev:     {
bot:dev:       code: 'invalid_type',
bot:dev:       expected: 'object',
bot:dev:       received: 'undefined',
bot:dev:       path: [],
bot:dev:       message: 'Required'
bot:dev:     }
bot:dev:   ],
bot:dev:   addIssue: [Function (anonymous)],
bot:dev:   addIssues: [Function (anonymous)],
bot:dev:   errors: [
bot:dev:     {
bot:dev:       code: 'invalid_type',
bot:dev:       expected: 'object',
bot:dev:       received: 'undefined',
bot:dev:       path: [],
bot:dev:       message: 'Required'
bot:dev:     }
bot:dev:   ]
bot:dev: }
```
I'm not entirely sure what DMMF is, but my prisma client doesn't have a `p.dmmf` field.

`Property 'dmmf' does not exist on type 'typeof import("C:/Users/ben/OneDrive/Desktop/remake/packages/database/dist/index")'.ts(2339)`

I am exporting the prisma client in a monorepo package called "database" as follows:
`export * from "@prisma/client";`
and then importing it into my apps using `import * as p from "database";`

I have of course ran prisma generate, etc and my schema is generated and up to date.

**Comment by franky47** [comment]
I see, it's indeed the DMMF (the internal representation of your Prisma schema as a JS object) that's missing.

Sounds like you'll need to export it alongside your Prisma Client in your database package, and import it and pass it to the fieldEncryptionExtension.

So basically, this section of the docs, but adapted for your monorepo setup:
https://github.com/47ng/prisma-field-encryption?tab=readme-ov-file#custom-prisma-client-location

**Comment by MonkeeMan1** [comment]
> I see, it's indeed the DMMF (the internal representation of your Prisma schema as a JS object) that's missing.
> 
> Sounds like you'll need to export it alongside your Prisma Client in your database package, and import it and pass it to the fieldEncryptionExtension.
> 
> So basically, this section of the docs, but adapted for your monorepo setup: https://github.com/47ng/prisma-field-encryption?tab=readme-ov-file#custom-prisma-client-location

Thank you so much, this resolved my problem :)
