### ISSUE TITLE
`connectOrCreate` query seems to be encrypted twice?

### ISSUE THREAD

**Issue by evoactivity** [47ng/prisma-field-encryption#15]
I'm adding this to an already working app.

If I have a booking model with a relation to a user model and I do something like

```javascript
const newBookingAndUser = await prisma.booking.create({
  data: {
    ...bookingData,
    users: {
      connectOrCreate: [{
        where: {
          email: 'someemail@email.com'
        },
        create: {
          name: 'Some name',
          email: 'someemail@email.com'
        }
      }]
    }
  },
  include: {
    users: true
  }
});

const booking = await prisma.booking.findUnique({
  where: { id: newBookingAndUser.id },
  include: { users: true}
});

// OR

const user = await prisma.user.findUnique({ where: { id: newBookingAndUser.users[0].id } })

```
In this example only the name field on the user should be encrypted.
The encrypted fields in the user object appear to return the encrypted string, but when I compare the output to what is stored in the database it's not the same value, suggesting the value in the db is being decrypted, but into a previously encrypted string.

**Comment by franky47** [comment]
Do you have any error logs showing decryption errors? Also, do you have any other middlewares, and what is their order?

**Comment by evoactivity** [comment]
Sorry, I just tried to add a failing test to the integration tests in this repo but they pass. I'll do some more digging and if I find more information I'll post or close this depending on where I need to apply the fix.

**Comment by franky47** [comment]
Thanks, let me know, I'm interested in your findings!

I did add a bypass for decryption on read when the model being queried has no encrypted fields (as is the case here), but it should detect the `include` clause and decrypt nonetheless.

Just to rule that out, you can disable that feature by commenting the `return` in `node_modules/prisma-field-encryption/dist/encryption.js:74`.

**Comment by evoactivity** [comment]
It seems like one of my arrays is being mutated by the encryption process.

```js
const userDtos = [];

booking.users.forEach((user) => {
  userDtos.push({
    where: {
      email: user.email.toLowerCase()
    },
    create: { ...user.toJSON(), email: user.email.toLowerCase() }
  });
});

const newBooking = await this.booking.create({
  data: {
    ...BookingMapper.toDatabase(booking),
    id: booking.id,
    users: { connectOrCreate: userDtos }
  },
  include: {
    users: true
  }
});

// something happens here outside of my control, I don't modify or access userDtos until
// further in the code, and now userDtos[0].create.name will be the encrypted string instead of 
// the originally defined unencrypted string
// so now when I run this code it is sending encrypted strings

const received = await this.user.update({
  where: {
    email: newBooking.users[0].email
  },
  data: userDtos[0].create
});

```

Changing my connectOrCreate to `users: { connectOrCreate: JSON.parse(JSON.stringify(userDtos)) }` fixes my immediate bug.

**Comment by franky47** [comment]
Ah yes, this is related to an issue where Prisma middlewares can't (couldn't?) replace the params to perform immutable changes.

See https://github.com/47ng/prisma-field-encryption/issues/3 and discussion on Prisma: https://github.com/prisma/prisma/discussions/10446

**Comment by evoactivity** [comment]
Following the discussions you linked it looks like the changes needed in prisma have now been merged. Is #3 something that it likely to be looked at again anytime soon?

**Comment by evoactivity** [comment]
No problem, I hope you feel better soon!

**Comment by evoactivity** [comment]
Wow! That was much quicker than expected!

My tests now pass without `JSON.parse(JSON.stringify(x))` so it seems to be working as expected :) Thank you for taking a look at this, especially when ill!
