### ISSUE TITLE
Support custom path of PrismaClient

### ISSUE THREAD

**Issue by pwdevbcf** [47ng/prisma-field-encryption#19]
Is there a possibility to add support for custom path of prisma client? 

I am using prisma client like that: `import { PrismaClient } from './prisma/dir/generated/generalClient';`

because of multiple connections. 
Is there any possibility to add new configuration property like: 
```
prisma.$use(fieldEncryptionMiddleware(
prismaClient: mainPrismaClient
))
```

because @prisma/client is not that much flexible

**Comment by franky47** [comment]
Duplicate of #18, let's move the discussion there.
