### ISSUE TITLE
'asc' and 'desc' are encrypted when using orderBy on String values

### ISSUE THREAD

**Issue by forbesgillikin** [47ng/prisma-field-encryption#43]
```js
prisma.user.findMany({
        where: {
            archived: false
        },
        take: 25,
        skip: 0,
        orderBy: {
           lastName: 'asc'
        }
    })
```

lastName is _**not**_ encrypted in the Prisma model.

`'asc'` becomes encrypted when passed into Prisma

`Argument lastName: Provided value '*encryptedvalue*' of type String on prisma.findManyUser is not a SortOrder.`

Using SortOrders on other types works as expected.

**Comment by franky47** [comment]
May I see the relevant Prisma model in your schema please, with the `@encrypted` annotations?

**Comment by forbesgillikin** [comment]
In my OP I referenced a different model but this is the one of concern in my project

```prisma
model Card {
  id               String         @id @default(uuid())
  createdAt        DateTime       @default(now())
  updatedAt        DateTime       @updatedAt
  cardID           String         @unique /// @encrypted
  cardIDHash       String?        @unique /// @encrypted:hash(cardID)
  cardNumber       String         @unique /// @encrypted
  cardNumberHash   String?        @unique /// @encrypted:hash(cardNumber)
  date             DateTime       @default(now())
  firstName        String
  lastName         String
  email            String?
  lastPaid         DateTime?      @default(now())
  lastPaidAmount   Float?
  archived         Boolean        @default(false)
  cardHolderTypeId String
  cardHolderType   CardHolderType @relation(fields: [cardHolderTypeId], references: [id], onDelete: Cascade, onUpdate: Cascade)
  transactions     Transaction[]
}
```

```js
const cards = await prisma.card.findMany({
        where: {
            archived: false,
            cardHolderType: cardHolderType
                ? { name: cardHolderType }
                : { isNot: undefined }
        },
        include: {
            cardHolderType: true,
            transactions: true
        },
        take: 25,
        skip: page > 1 ? (page - 1) * 25 : 0,
        orderBy: {
             lastName: 'asc'
        }
    })
```


`'asc'` gets converted into an encrypted string. When using `orderBy` with non-supported types like ID, Float, DateTime, `'asc'` is not converted to an encrypted string and Prisma resolves as expected.

**Comment by franky47** [comment]
What do the [debugging](https://github.com/47ng/prisma-field-encryption#debugging) logs say? I'd be curious to see what the schema analysis looks like, to understand how this path ends up being encrypted, especially on a read-only query.

**Comment by codewithmecoder** [comment]
Hi @franky47

I got the same error. 
The error is:
```json
{
    "statusCode": 500,
    "error": "Internal Server Error",
    "message": "\nInvalid `prisma.user.findMany()` invocation in\nC:\\projects\\fastify-test\\src\\modules\\user\\user.service.ts:30:22\n\n  27 }\n  28 \n  29 export async function findUsers() {\n→ 30   return prisma.user.findMany({\n         select: {\n           email: true,\n           name: true,\n           id: true,\n           createdAt: true,\n           expiredAt: true\n         },\n         orderBy: {\n           email: 'v1.aesgcm256.d2a16aa0.uYZkVsBGJYUxarPL.MlYUnc9DVYnZN1FQ4mU3Js-wDd0=',\n                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n           emailHash: 'c3f46fc280c4ac3e5724798b684c86b04d0bc217adcfcb1dade3c1ef56fd8e6b'\n                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n         }\n         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n       })\n\nArgument orderBy of type UserOrderByWithRelationInput needs exactly one argument, but you provided email and emailHash. Please choose one. Available args: \ntype UserOrderByWithRelationInput {\n  id?: SortOrder\n  email?: SortOrder\n  emailHash?: SortOrder\n  name?: SortOrder\n  password?: SortOrder\n  salt?: SortOrder\n  createdAt?: SortOrder\n  updatedAt?: SortOrder\n  expiredAt?: SortOrder\n  products?: ProductOrderByRelationAggregateInput\n}\nArgument email: Provided value 'v1.aesgcm256.d2a16aa0.uYZkVsBGJYUxarPL.MlYUnc9DVYnZN1FQ4mU3Js-wDd0=' of type String on prisma.findManyUser is not a SortOrder.\n→ Possible values: SortOrder.asc, SortOrder.desc\nArgument emailHash: Provided value 'c3f46fc280c4ac3e5724798b684c86b04d0bc217adcfcb1dade3c1ef56fd8e6b' of type String on prisma.findManyUser is not a SortOrder.\n→ Possible values: SortOrder.asc, SortOrder.desc\n\n"
}
```

**Comment by franky47** [comment]
Thanks for the debug logs, I can see where the problem is now. I'll have to add a test case for the presence of `orderBy` in the query, but it will also need to apply this sorting logic not at the database level (which makes no sense as we'd be sorting the ciphertext), but at runtime after decryption.

**Comment by franky47** [comment]
I'm closing this as "won't fix", as sorting on encrypted values is not something I'd recommend: since the database cannot do the job itself (sorting random ciphertext won't do much good for sorting the underlying clear text data), sorting would have to be done at runtime after decryption, which is another whole can of worms of parsing the query to know what to work on.

If anyone wishes to tackle this problem, I'll happily review PRs.

In the mean time, attempting to `orderBy` on an encrypted field will log an error, and fix the encrypted 'asc' | 'desc' issue so that Prisma doesn't complain (it will actually drop the `orderBy` clause).

As for @forbesgillikin and @codewithmecoder, if you're indeed sorting on non-encrypted fields and see this error, please provide me with debug logs so I can have a better idea of what is going on.
