### ISSUE TITLE
Remove error for `interactiveTransactions`

### ISSUE THREAD

**Issue by gokulkrishh** [47ng/prisma-field-encryption#47]
BG: Prisma gives this warning when we use `interactiveTransactions` in previewFeatures. 

`warn Preview feature "interactiveTransactions" is deprecated. The functionality can be used without specifying it as a preview feature.`

This feature is available in general now, can we remove the error in this module when not present?

**Comment by franky47** [comment]
Looks like it went into GA in version [`4.7.0`](https://github.com/prisma/prisma/releases/tag/4.7.0), that's great news!

However, for the sake of compatibility with previous versions, it would be wise to keep the check for 4.6.1 and under. I don't know if the Prisma client version can be determined at runtime, but if can that'd be the way to go.

Would you like to open a PR?

**Comment by gokulkrishh** [comment]
@franky47 Sure, let me see if we can detect features available or version of prisma to remove the limiters for preview feature.

**Comment by gokulkrishh** [comment]
@franky47 I went through docs to see if we can figure out the version during the run time. looks like there isn't one.

Either we have to wait until 4.6.0 is deprecated or remove this in latest version of `prisma-field-encryption` as it doesn't make sense to have this since dependant library made the preview feature public.

Will let you take a call on this.

**Comment by franky47** [comment]
I guess we could:
1. Remove the check that leads to an error
2. Make it clear in the docs that the preview feature is required for Prisma Client 3.8.0 to 4.6.1, in the data migrations section.

**Comment by gokulkrishh** [comment]
@franky47 Sure, sounds good. I will raise a PR then. Thanks.

**Comment by gokulkrishh** [comment]
@franky47 Here is [PR](https://github.com/47ng/prisma-field-encryption/pull/48) for the same
