### ISSUE TITLE
UnhandledSchemeError: Reading from "node:crypto" is not handled by plugins (Unhandled scheme).

### ISSUE THREAD

**Issue by 0xSmartCrypto** [47ng/prisma-field-encryption#56]
Hi @franky47 - I tried `prisma-field-encryption` and it worked great for 
- prisma.table.create
- prisma.table.findUnique

But when I tried prisma.table.update, I got a build error:

```
error - node:crypto
Module build failed: UnhandledSchemeError: Reading from "node:crypto" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "node:" URIs.
Import trace for requested module:
node:crypto
./node_modules/prisma-field-encryption/dist/hash.js
./node_modules/prisma-field-encryption/dist/encryption.js
./node_modules/prisma-field-encryption/dist/index.js
./lib/prisma.ts
```

I'm using Next 13.3.0, Prisma 4.12.0, prisma-field-encryption 1.4.1

**Comment by 0xSmartCrypto** [comment]
Made a blooper. This is actually working as intended.

**Comment by matheins** [comment]
IM also getting this error message. Whats the solution for it @0xSmartCrypto ?

**Comment by 0xSmartCrypto** [comment]
I'm not sure this was the "fix" but I had to ensure the column type had enough length.

E.g. 

// before
```
model Whatever {
  fieldName String /// @encrypted
}
```

// after
```
model Whatever {
  fieldName @db.LongText /// @encrypted
}
```
