### ISSUE TITLE
Uniqueness of field not respected.

### ISSUE THREAD

**Issue by mrwokkel** [47ng/prisma-field-encryption#7]
When using:
```
email             String   @unique /// @encrypted
```
The uniqueness of the field is not respected.

**Comment by mrwokkel** [comment]
Nevermind, my fault, should have read the manual. It is an awesome library!

Happy holidays!

**Comment by franky47** [comment]
Encrypted values should be unique, as it's extremely unlikely that two inputs result to the same ciphertext.
