### ISSUE TITLE
[mongo]: Hashes are not computed

### ISSUE THREAD

**Issue by Ahmadre** [47ng/prisma-field-encryption#79]
I created a brand new little nodejs project and installed prisma + this package.

After creating a document in my MongoDB Atlas (normal mongodb+srv connection), Hashes are not computed...

<img width="750" alt="Bildschirmfoto 2023-08-28 um 01 11 23" src="https://github.com/47ng/prisma-field-encryption/assets/18512224/41044995-ba67-40c7-81b8-48da0e03922b">

is this a bug?

Because as I know: Mongo is not saving nullable fields into the db. But I don't know why prisma is not computing the hashes...

**Comment by Ahmadre** [comment]
Notice: I've added the `@default("")` fields to try to fix this, but it also didn't work...

<img width="715" alt="Bildschirmfoto 2023-08-28 um 01 14 02" src="https://github.com/47ng/prisma-field-encryption/assets/18512224/0deef1c5-1208-45b7-ace4-d4db76de28c9">

**Comment by franky47** [comment]
Do you have a reproduction repository?

**Comment by Ahmadre** [comment]
> Do you have a reproduction repository?

If you give me your gitlab.com username or email I can add you to the project. Just write me via rebar.ahmad@gmail.com

**Comment by franky47** [comment]
I think I found the issue: the annotation for hash fields should be `/// @encryption:hash(fieldName)`, not `/// @encrypted:hash(fieldName)`.

**Comment by Ahmadre** [comment]
> I think I found the issue: the annotation for hash fields should be `/// @encryption:hash(fieldName)`, not `/// @encrypted:hash(fieldName)`.

you're totally right 🙈.

Thank you for your finding ❤️.
