### ISSUE TITLE
Feature request: HMAC Support for Hashing

### ISSUE THREAD

**Issue by ilim0t** [47ng/prisma-field-encryption#84]
Upon reviewing the hashing portion of the current code, I noticed that it does not include support for HMAC.
https://github.com/47ng/prisma-field-encryption/blob/62055f48fbdc392711bc6dd76fcdaef738a0464d/src/hash.ts#L12

To fortify the security capabilities of the library, I propose the addition of an option to use HMAC.
(Perhaps use: `crypto.createHmac`)

Benefits:
1. Implementing HMAC support enhances security. HMAC is notably known for its strengths in terms of security for data integrity and authentication.
2. It increases versatility for users in terms of their choice of hashing methods.

If there's a demand for this feature, I would be more than happy to create a pull request to implement it.

Please share your thoughts and feedback regarding this proposal.

**Comment by franky47** [comment]
> Implementing HMAC support enhances security. HMAC is notably known for its strengths in terms of security for data integrity and authentication.

HMAC is not a hash function (though it is based on them), it's a key derivation function. There's an important difference in how they are used, especially on untrusted, low-entropy inputs.

The only valid reason I can think of for using HMAC here is its keyed property. This would allow separating values across rows by specifying domain-separation keys. A dedicated keyed hash algorithm would be more suitable, but I don't think the `crypto.createHash`method supports providing a key, even if the underlying algorithm would support it.

Using a keyed hash could be interesting for multi-tenant applications, to guarantee isolation of identical values across tenants (eg: an email of `foo.bar@example.com` on two tenant instances would result in different hashes if keyed with different keys.

This raises the problem of "how to specify the key", as the hash operation is currently independent from the data it's applied to.

**Comment by ilim0t** [comment]
As you pointed out, the use of HMAC is indeed greatly beneficial for multi-tenant applications. However, I believe that its implementation can also enhance security even in a single-tenant environment.

By using a single key to generate the HMAC, it becomes highly effective in enhancing security, such as preventing unauthorized tampering.

In light of these considerations, how about initially implementing an option to generate HMAC using a single key?

**Comment by franky47** [comment]
> By using a single key to generate the HMAC, it becomes highly effective in enhancing security, such as preventing unauthorized tampering.

I'm not sure I follow your reasoning here. Could you describe your threat model?

Anyway, I'll happily review a PR if you want to have a go at implementing it.

**Comment by ilim0t** [comment]
Thank you for your reply.

I think the proposal for HMAC can address the threat model outlined below:

Consider a scenario where a large number of hash values from the database are leaked.
With the use of a conventional hash function, adversaries could conduct offline brute force attacks, or utilize rainbow tables to retrieve the plaintext.

However, when utilizing HMAC, unless the secret key is leaked, conducting these attacks becomes significantly challenging for attackers. As long as the secret key remains secure, the safety of the data is further enhanced.

**Comment by franky47** [comment]
If salting the hash is what you're after, this is already supported by the library, see the [documentation](https://github.com/47ng/prisma-field-encryption#hashing-options).
