### ISSUE TITLE
Filter with "contains"

### ISSUE THREAD

**Issue by multipliedtwice** [47ng/prisma-field-encryption#93]
Hello, thank you for an amazing library. How can I enable "contains" filtering, if it's possible?

**Comment by franky47** [comment]
As stated in the [filtering documentation](https://github.com/47ng/prisma-field-encryption#filtering-using-where) (emphasis added):

> This is because the encryption is not deterministic: encrypting the same input multiple times will yield different outputs, due to the use of random initialisation vectors to keep ciphertext safe. Therefore Prisma cannot match the query to the data.
> 
> To circumvent this issue, the extension provides support for a separate field containing a hash of the clear-text input, which is stable and can be used for exact matching _**(partial matching like startsWith, contains is not possible)**._

**Comment by danil-iglu** [comment]
Thank you, looks like in this case client side search would be the easiest option
